"use strict";
exports.__esModule = true;
var fs = require("fs");
var fileName = "./reto-1/users.txt";
var fileContent = fs.readFileSync(fileName, "utf8");
var campos = ["usr", "eme", "psw", "age", "loc", "fll"];
var strline = "";
var user;
var cantidad = 0;
var usuarios = [];
usuarios = fileContent.split("\n\n").filter(function (value) { return campos.every(function (camp) { return value.includes(camp); }); });
cantidad = usuarios.length;
strline = usuarios[cantidad - 1];
user = strline.split(/\n|\s/).map(function (chunk) { return chunk.split(":"); });
var map = new Map(user);
console.log(cantidad.toString() + map.get('usr'));
